project1/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.wiki, name="wiki"),
    path("add", views.add, name="add"),
    path("search", views.search, name="search"),
    path("random", views.random, name="random"),
    path("edit/<str:entry>", views.edit, name="edit")
]

project1/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

project1/encyclopedia/views.py
from django.shortcuts import redirect, render
from django import forms
import markdown2
from . import util
from random import choice

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def wiki(request, entry):
    markdown = util.get_entry(entry)
    if not markdown:
        return render(request, "encyclopedia/not_found.html", {
            "entry": entry
        })
    html = markdown2.markdown(markdown)
    return render(request, "encyclopedia/wiki.html", {
        "entry": entry,
        "markdown": html
    })

def search(request):
    entry = request.GET.get("q")
    if not entry:
        return render(request, "encyclopedia/search.html", {"error": "Please enter a search term",})
    entries = util.list_entries()
    results = []
    for e in entries:
        if entry.lower() == e.lower():
            return redirect("encyclopedia:wiki", entry)
        elif entry.lower() in e.lower():
            results.append(e)
    if len(results) == 0:
        return render(request, "encyclopedia/search.html", {
            "error": "No results found",
            "entry": entry})
    return render(request, "encyclopedia/search.html", {
        "results": results,
        "entry": entry
    })

class NewEntryForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Title", "class": "mb-4 mt-3 form-control w-25"}), label="")
    markdown = forms.CharField(widget=forms.Textarea(attrs={"class": "d-block form-control w-75 mb-4"}), label="")

def add(request):
    if request.method == "GET":
        return render(request, "encyclopedia/add.html", {
            "form": NewEntryForm()
        })
    elif request.method == "POST":
        form = NewEntryForm(request.POST)
        if not form.is_valid():
            return render(request, "encyclopedia/add.html", {
                "form": form,
                "error": "Invalid form"
            })
        title = form.cleaned_data["title"]
        markdown = form.cleaned_data["markdown"]
        already_exists = title.lower() in (string.lower() for string in util.list_entries())
        if already_exists:
            return render(request, "encyclopedia/add.html", {
                "form": NewEntryForm(request.POST),
                "error": "Entry already exists"
            })
        util.save_entry(title, markdown)
        return redirect("encyclopedia:wiki", title)

def random(request):
    entries = util.list_entries()
    entry = choice(entries)
    return redirect("encyclopedia:wiki", entry)

class NewEditForm(forms.Form):
    markdown = forms.CharField(widget=forms.Textarea(attrs={"class": "d-block form-control w-75 mb-4"}), label="")
    title = forms.CharField(widget=forms.HiddenInput())

def edit(request, entry):
    if request.method == "GET":
        return render(request, "encyclopedia/edit.html", {
            "title": entry,
            "form": NewEditForm(initial={"title": entry, "markdown": util.get_entry(entry)})
        })
    elif request.method == "POST":
        form = NewEditForm(request.POST)
        if not form.is_valid():
            return render(request, "encyclopedia/edit.html", {
                "form": form,
                "error": "Invalid form"
            })
        title = form.cleaned_data["title"]
        markdown = form.cleaned_data["markdown"]
        util.save_entry(title, markdown)
        return redirect("encyclopedia:wiki", title)

project1/encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Add
{% endblock %}

{% block body %}
    
    <h1>Add New Entry</h1>
    
    <form action="{% url 'encyclopedia:add' %}" method="post">
        {% csrf_token %}
        <h2>{{ error }}</h2>
        {{ form }}
        <input class="form-control w-25" type="submit" value="Add Entry">
    </form>
{% endblock %}

project1/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit
{% endblock %}

{% block body %}

    <h1>Editing <em>{{ title }}</em></h1>

    <form action="{% url 'encyclopedia:edit' title %}" method="post">
        {% csrf_token %}
        <h2>{{ error }}</h2>
        {{ form }}
        <input class="form-control w-25" type="submit" value="Edit Entry">
    </form>
{% endblock %}

project1/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:wiki' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

project1/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}">
                    <input class="search form-control" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add' %}">Add New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

project1/encyclopedia/templates/encyclopedia/not_found.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    404 Not Found
{% endblock %}

{% block body %}
    
    <h1>The requested entry <em>{{ entry }}</em> was not found. </h1>

    <h3 class="font-weight-normal">You may create an entry <a href="{% url 'encyclopedia:add' %}">here</a></h3>

{% endblock %}

project1/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search: {{ entry }}
{% endblock %}

{% block body %}
    <h1>Search Results: <span class="font-italic">{{ entry }}</span></h1>
    <h2>{{ error }}</h2>
    <ul>
    {% for result in results %}
        <li><a href="{% url 'encyclopedia:wiki' result %}">{{ result }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}

project1/encyclopedia/templates/encyclopedia/wiki.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry }}
{% endblock %}

{% block body %}
    <a href="/edit/{{ entry }}" class="edit"><h4>Edit</h4></a>

    {{ markdown|safe }}

{% endblock %}