week3/hello/urls.py
from django.urls import path
from . import views

app_name = "hello"
urlpatterns = [
    path("", views.index, name="index"),
    path("world", views.world, name="world"),
    path("<str:name>", views.greet, name="greet")
]

week3/newyear/urls.py
from django.urls import path
from . import views

app_name = "newyear"
urlpatterns = [
    path("", views.index, name="index")
]

week3/tasks/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

week3/week3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hello/", include("hello.urls")),
    path("newyear/", include("newyear.urls")),
    path("tasks/", include("tasks.urls")),
]

week3/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def index(request, name):
    return render(request, "hello/index.html", {"name": name})

def world(request):
    return HttpResponse("Hello, World!")

def greet(request, name):
    return HttpResponse(f"Hello {name.capitalize()}!")

week3/newyear/views.py
from django.shortcuts import render
import datetime 

# Create your views here.

def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

week3/tasks/views.py
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django import forms

# Create your views here.

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method =="POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })
    
    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

week3/hello/templates/hello/index.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        <h1>Hello, {{ name }}</h1>
    </body>
</html>

week3/newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Is it New Year's?</title>
        <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
    </head>
    <body>
        {% if newyear %}
            <h1>Yes</h1>
        {% else %}
            <h1>No</h1>
        {% endif %}
    </body>
</html>

week3/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Add Task:</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

week3/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Tasks:</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add a new task</a>
{% endblock %}

week3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>